### ISSUE TITLE
Rename everything from PushJet to PushFish

### ISSUE THREAD

**Issue by VoliKoN** [PushFish/pushfish-android#7]
Readme should also be updated

**Comment by madsalama** [comment]
Can I work on this?

**Comment by Leopere** [comment]
Thanks to @nish-d in https://github.com/PushFish/pushfish-android/pull/8 we can call this completed.

**Comment by jsonvillanueva** [comment]
It's worth note, the current application uses io.pushfish.api when the organization domain is push.fish... We will likely have the api.push.fish subdomain and need to change the pkg to fit fish.push.api to fit naming convention

**Comment by Leopere** [comment]
@jsonvillanueva good to note, I imagine that we shouldn't have that hardcoded for any reason anyways.  May be a good GitLab issue to post @jsonvillanueva

**Comment by VoliKoN** [comment]
This is not done yet, there's still a lot of pushjet mentions:
https://github.com/PushFish/pushfish-android/search?q=pushjet&unscoped_q=pushjet
Also it should point to api.push.fish as default.

@Leopere can you reopen this, I cant for some reason...

**Comment by VoliKoN** [comment]
Done in #9
